### PR TITLE
Fix178

### LINKED ISSUE #178: AUTH48: Wrong use of HTTP Proxy
Section 4.1 contains:

"If the recipient is configured to use another HTTP proxy, it will act as an intermediary by forwarding the request to another HTTP server."

There are some potential issues in this sentence. First is the usage of "HTTP Proxy". So the recipient of an Connect-IP request can either be an client side HTTP intermediary, in which case it will route and connect to next hop per host header. It might be the IP Proxy, or it can be a receiver side HTTP Intermediary in which case it will forward according to internal policies. Thus, I think this sentence needs to be rewritten so that it correctly reflect what I think is meant here. Maybe something like:

If the recipient is an HTTP intermediary, it will forward the request to next hop HTTP Intermediary or HTTP Server (IP Proxy).

### PR DESCRIPTION
**Pull request by DavidSchinazi**
Fixes #178

### CODE REVIEW

**Comment by gloinul** [comment]
So this is better, but I would note that the sentence ("If the recipient is configured to use another HTTP server ...") is actually biased towards an HTTP Gateway, i.e. an HTTP server side HTTP Intermediary rather than also cover client side HTTP Proxy. As this type of proxies the client are configured to use them, but they will process the HTTP request and determine how to forward it based on the host information in the request.

**Review by tfpauly — APPROVED** [review]

**Comment by DavidSchinazi** [comment]
@gloinul I agree with you that the common instance is that of a gateway, but the term intermediary is also correct. Are you suggesting a change to this PR or are you OK with it?

**Comment by gloinul** [comment]
I think it is the word "configure" that I have issue with. As the recipient doesn't need to be configured to use another HTTP server, just to be a HTTP intermediary. I think what would be clearer are:

"If the recipient is configured to be an HTTP intermediary, it will forward the request to a HTTP server or another HTTP intermediary." 

This sentence is just to provide a context for when the following note applies.

**Comment by DavidSchinazi** [comment]
> If the recipient is configured to be an HTTP intermediary, it will forward the request to a HTTP server or another HTTP intermediary.

That's not quite right, an HTTP intermediary is an HTTP server - the server is simply [defined](https://www.rfc-editor.org/rfc/rfc9110#section-3.3) as the one who receives the request and sends the response. In other words, an intermediary is both an HTTP client and an HTTP server, but in this case it's the server half that's relevant. So it doesn't make sense to say "to a HTTP server or another HTTP intermediary".

We could therefore imagine saying the following:
> If the recipient is configured to be an HTTP intermediary, it will forward the request to another HTTP server.

But at that point I prefer the text in this PR, I find it more clear.

**Comment by DavidSchinazi** [comment]
@gloinul do you have any more thoughts? This is the last remaining discussion point, it would be nice for us to resolve it.

**Pull request merged**
